---
title: "minimisation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library
```{r, message=FALSE}
library(tidyverse)
library(ggplot2)
```

## Dataset

I assume that there are 3 strata, A, B, and C. A andC have two levels while B has 3. These levels are sampled with an equal probability in each stratum.

Treatment column which includes only NA is combined to complete the dataset.

```{r}
# sample size
# Later on counting may fail if a sample size is small and not all levels in starata exist in the dataset
n<-1000

# Create each column of the dataset of enrolling patient
s.a <- sample(1:2, size = n, replace = TRUE, prob = c(0.5, 0.5)) # StratumA
s.b <- sample(1:3, size = n, replace = TRUE, prob = c(1/3, 1/3, 1/3)) #StratumB
s.c <- sample(1:2, size = n, replace = TRUE, prob = c(0.5, 0.5)) #StratumC

# Combine the columns
d <- data.frame(ptid = 1:n, 
                StratumA = s.a, 
                StratumB = s.b, 
                StratumC = s.c, 
                Treatment = matrix(NA,nrow = n, ncol = 1)) # Empty column for treatment allocation

```

Let's check if each stratum has a even distribution of levels.

```{r}
# Check the patient background
d %>%
  select(ptid, StratumA, StratumB, StratumC) %>%
  pivot_longer(cols = -ptid, names_to = "Strata", values_to = "level") %>%
  ggplot(., aes(x = as.factor(level))
  ) + geom_bar(
  ) + facet_wrap(~Strata, scales = 'free_x'
  ) + ggtitle(paste("sample n=",n))
```

